#!/bin/bash

HERE=$(pwd)

#VERSION=$(grep "csVersion ="  ${HERE}/../src/qBitTorrentWebUI.pas | cut -d\' -f2)
VERSION="0.1"

LPIFILE=${HERE}/src/lazJSONViewer.lpi

DISTPATH=${HERE}/bin/dist

DIRLIN64=${HERE}/bin/linux/x86_64
LOGLIN64=${DISTPATH}/LogLin64.txt

DIRLIN32=${HERE}/bin/linux/i386
LOGLIN32=${DISTPATH}/LogLin32.txt

DIRLINARM=${HERE}/bin/linux/arm
LOGLINARM=${DISTPATH}/LogLinarm.txt

BINLINUX=lazJSONViewer

DIRWIN32=${HERE}/bin/win32/i386
LOGWIN32=${DISTPATH}/LogWin32.txt

DIRWIN64=${HERE}/bin/win64/x86_64
LOGWIN64=${DISTPATH}/LogWin64.txt

BINWIN=lazJSONViewer.exe

LAZBUILD=~/FreePascal/lazarus/lazbuild

DISTNAME=lazJSONViewer

ARCH=$(uname -m)

#echo ${HERE}
#echo ${DIRLIN32}/${BINLINUX}
#echo ${DIRLIN64}/${BINLINUX}
#echo ${DIRLINARM}/${BINLINUX}
#echo ${DIRWIN32}/${BINWIN}
#echo ${DIRWIN64}/${BINWIN}
#echo ${VERSION}

echo Cleaning dist
rm ${HERE}/bin/dist/*

if [ ${ARCH} == "armv7l" ]; then

echo Cleaning linux arm
rm ${DIRLINARM}/${BINLINUX}

else

echo Cleaning linux 32
rm ${DIRLIN32}/${BINLINUX}

echo Cleaning linux 64
rm ${DIRLIN64}/${BINLINUX}

echo Cleaning win32
rm ${DIRWIN32}/${BINWIN}

echo Cleaning win64
rm ${DIRWIN64}/${BINWIN}

fi

echo "Laz JSON Viewer v${VERSION}"

if [ ${ARCH} == "armv7l" ]; then

echo Building Linux ARM
$LAZBUILD -B --bm=Release ${LPIFILE} 2>&1 > ${LOGLINARM}

if [ -f ${DIRLINARM}/${BINLINUX} ]; then
  echo "  Found Linux ARM"
  pushd ${DIRLINARM} > /dev/null
  echo "  Stripping ${BINLINUX}"
  strip ${BINLINUX}
 echo " Packaging ${DISTPATH}/${DISTNAME}-${VERSION}-linux-arm.tgz"
  echo "---"
  tar -v --gzip --create --file ${DISTPATH}/${DISTNAME}-${VERSION}-linux-arm.tgz ${BINLINUX}
  echo "---"
  popd > /dev/null
else
  echo "  Linux ARM NOT found"
fi

else

echo Building Linux 32
$LAZBUILD -B --bm=Release-linux-i386 ${LPIFILE} 2>&1 > ${LOGLIN32}

if [ -f ${DIRLIN32}/${BINLINUX} ]; then
  echo "  Found Linux 32"
  pushd ${DIRLIN32} > /dev/null
  echo "  Stripping ${BINLINUX}"
  strip ${BINLINUX}
 echo " Packaging ${DISTPATH}/${DISTNAME}-${VERSION}-linux-i386.tgz"
  echo "---"
  tar -v --gzip --create --file ${DISTPATH}/${DISTNAME}-${VERSION}-linux-i386.tgz ${BINLINUX}
  echo "---"
  popd > /dev/null
else
  echo "  Linux 32 NOT found"
fi

echo Building Linux 64
$LAZBUILD -B --bm=Release --os=Linux --cpu=x86_64 ${LPIFILE} 2>&1 > ${LOGLIN64}

if [ -f ${DIRLIN64}/${BINLINUX} ]; then
  echo "  Found Linux 64"
  pushd ${DIRLIN64} > /dev/null
  echo "  Stripping ${BINLINUX}"
  strip ${BINLINUX}
  echo "  Packaging ${DISTPATH}/${DISTNAME}-${VERSION}-linux-x86_64.tgz"
  echo "---"
  tar -v --gzip --create --file ${DISTPATH}/${DISTNAME}-${VERSION}-linux-x86_64.tgz ${BINLINUX}
  echo "---"
  popd > /dev/null
else
  echo "  Linux 64 NOT found"
fi

echo Building Win32
$LAZBUILD -B --bm=Release --os=win32 --cpu=i386 ${LPIFILE} 2>&1 > $LOGWIN32

if [ -f ${DIRWIN32}/${BINWIN} ]; then
  echo "  Found Win32"
  pushd ${DIRWIN32} > /dev/null
  echo "  Packaging ${DISTPATH}/${DISTNAME}-${VERSION}-win32.zip"
  echo "---"
  zip  ${DISTPATH}/${DISTNAME}-${VERSION}-win32.zip ${BINWIN}
  echo "---"
  popd > /dev/null
else
  echo "  Win32 NOT found"
fi

echo Building Win64
$LAZBUILD -B --bm=Release --os=win64 --cpu=x86_64 ${LPIFILE} 2>&1 > $LOGWIN64

if [ -f ${DIRWIN64}/${BINWIN} ]; then
  echo "  Found Win64"
  pushd ${DIRWIN64} > /dev/null
  echo "  Packaging ${DISTPATH}/${DISTNAME}-${VERSION}-win64.zip"
  echo "---"
  zip  ${DISTPATH}/${DISTNAME}-${VERSION}-win64.zip ${BINWIN}
  echo "---"
  popd > /dev/null
else
  echo "  Win64 NOT found"
fi

fi
